---
title: "Beaked whale click detection"
format: html
editor: visual
---

### Classification

------------------------------------------------------------------------

```{r}
#| message: false
#| warning: false

library(arrow)
library(tidyverse)
library(ppclust)
library(factoextra)
library(cluster)
library(fclust)
```

Attempting to translate Sam's Julia code into R.

```{r}
#read in a feather file
clicks <- arrow::read_feather(here::here("data/features_20190529.feather"))
#every feather file holds a day

#transforming duration to log(duration) and selecting the four features that Sam used to cluster
clicks <- clicks %>% 
  mutate(logduration = log(duration)) %>% 
  select(logduration, peak_freq, peak_bw, freq50)

#subsample every n clicks
click_idx <- sample(1:nrow(clicks), 22200)
click_sub <- clicks[click_idx, ]

#normalize everything along 0-1
click_norm_sub <- (click_sub - min(click_sub)) / (max(click_sub) - min(click_sub))

#using fuzzy c means to classify the clicks into n clusters. Sam used 200 iterations and 15 clusters, fuzziness value of 2 (default in fcm). 
res.fcm <- fcm(click_norm_sub, centers = 15, iter.max = 200)
#Takes ~10 minutes to run. (When finished, it will print 'timing stopped at:' with 3 numbers, which indicate the user, system, and elapsed time.)

#looking at a data frame which says how much each click belongs to each cluster (because in fuzzy c means, you have partial membership to all clusters)
head(as.data.frame(res.fcm$u))

#summary statistics for the results
#summary(res.fcm)

#pairs plot of what clusters look like across features
plotcluster(res.fcm, cp = 1, trans = TRUE)

#turning the fcm object into a kmeans object to visualize coordinates
res.fcm2 <- ppclust2(res.fcm, "kmeans")

#visualize the clusters. geom = point takes away the labels
factoextra::fviz_cluster(res.fcm2, data = click_norm_sub, 
  ellipse.type = "convex",
  geom = "point", 
  ggtheme = theme_classic())
```
